### ISSUE TITLE
Extension doesn't work on the new Leetcode UI

### ISSUE THREAD

**Issue by ishaanbuildsthings** [eddgr/clip-leetcode#4]
Hi,

Thank you for making this extension. I believe it doesn't work on the new Leetcode UI, only the old one. Are there plans to change this?

**Comment by eddgr** [comment]
Hey there, can you link me to a page where it isn't working?

**Comment by samiullaansari** [comment]
Hi, Thanks for making such a great extension. It is working perfectly with old split view mode but not working with new dynamic layout. It would be great if it is implemented for new dynamic layout as well.

Here is how it can be set from the settings
![image](https://github.com/eddgr/clip-leetcode/assets/54569342/cb3ac30d-2b7a-4b40-8a0a-f2f91c60550c)

Below is an example of how new dynamic layout looks like
![image](https://github.com/eddgr/clip-leetcode/assets/54569342/2d49dbe6-7391-4ee9-bc48-f4bc97831eb0)

**Comment by eddgr** [comment]
Hey @aiwithsami is that a premium feature? Otherwise, I'm not sure how to access the page in your screenshot.

Also, feel free to submit a PR to support that layout!

**Comment by samiullaansari** [comment]
Hi @eddgr , It is not not a premium feature I guess. Option to enable it is there at the top right of the page.
![image](https://github.com/eddgr/clip-leetcode/assets/54569342/aa90bde9-d070-408b-b772-207e28f8f806)

https://leetcode.com/problems/longest-substring-without-repeating-characters/description/

**Comment by eddgr** [comment]
@aiwithsami awesome, thanks for clarifying!

Feature added in [this commit](https://github.com/eddgr/clip-leetcode/commit/0b994a98a9be6f9e8dfd8c50843ca6e4b96dfe45) and has been submitted for review in the Chrome Web Store!

**Comment by samiullaansari** [comment]
@eddgr wow, you are so fast. It is live now and working perfectly. Thanks!
