### ISSUE TITLE
Extension doesn't work on contest UI

### ISSUE THREAD

**Issue by ishaanbuildsthings** [eddgr/clip-leetcode#5]
Hi,

Thank you for making this extension. I believe it doesn't work on the new Leetcode UI, only the old one. Are there plans to change this? I would super appreciate it, the only time I code in my own IDE is for contest problems so it would be great if I could copy the markdown.

**Comment by eddgr** [comment]
Feature added in [this commit](https://github.com/eddgr/clip-leetcode/commit/0da319718c98c34d6e5be8c6d9bd9cf0d2808420) and has been submitted for review in the Chrome Web Store. 

Thanks for the feature request!

**Comment by ishaanbuildsthings** [comment]
Hey, thanks for both, you are so awesome! I'll use these every day once it's approved.
